version: '3.9'

services:
  escola-api:
    container_name: escola-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true
    environment: 
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      TZ: "America/Sao_Paulo"
    depends_on:
      - db
    links:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
  
  db:
    container_name: escola-db
    image: pamps_postgres-13-alpine-multi-user
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_PORT: ${DB_PORT}
        TZ: "America/Sao_Paulo"
    ports:
      - "5433:5432"
  